name: Dev Joke Workflow

on: 
  push:
    branches:
    - dev

jobs:
  joke_job:
    runs-on: ubuntu-latest
    steps:
    - name: Get some joke about IT
      run: |
        curl -X POST https://icanhazdadjoke.com/graphql \
         -H "Content-Type: application/json" \
         -d '{"query": "{ joke { id joke } }"}' || true
        - name: I am Ann and it is my first echo request
          run: echo "Workflow completed successfully"
