name: Dev Joke Workflow

on: 
  push:
    branches:
    - dev

jobs:
  joke_job:
    runs-on: ubuntu-latest
    steps:
    - name: Get some joke about IT
      run: curl -X POST https://v2.jokeapi.dev/submit
    - name: I am Ann and it is my first echo request
      run: echo "Workflow completed successfully"
